#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThanhThanh.DAL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="QLCuocDT")]
	public partial class QLCDTDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertCUOCTHUEBAO(CUOCTHUEBAO instance);
    partial void UpdateCUOCTHUEBAO(CUOCTHUEBAO instance);
    partial void DeleteCUOCTHUEBAO(CUOCTHUEBAO instance);
    partial void InsertTHONGTINSIM(THONGTINSIM instance);
    partial void UpdateTHONGTINSIM(THONGTINSIM instance);
    partial void DeleteTHONGTINSIM(THONGTINSIM instance);
    partial void InsertHOADON(HOADON instance);
    partial void UpdateHOADON(HOADON instance);
    partial void DeleteHOADON(HOADON instance);
    partial void InsertKHACHHANG(KHACHHANG instance);
    partial void UpdateKHACHHANG(KHACHHANG instance);
    partial void DeleteKHACHHANG(KHACHHANG instance);
    partial void InsertTHOIGIANSUDUNG(THOIGIANSUDUNG instance);
    partial void UpdateTHOIGIANSUDUNG(THOIGIANSUDUNG instance);
    partial void DeleteTHOIGIANSUDUNG(THOIGIANSUDUNG instance);
    #endregion
		
		public QLCDTDataContext() : 
				base(global::ThanhThanh.Properties.Settings.Default.QLCuocDTConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDTDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDTDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDTDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public QLCDTDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<CUOCTHUEBAO> CUOCTHUEBAOs
		{
			get
			{
				return this.GetTable<CUOCTHUEBAO>();
			}
		}
		
		public System.Data.Linq.Table<THONGTINSIM> THONGTINSIMs
		{
			get
			{
				return this.GetTable<THONGTINSIM>();
			}
		}
		
		public System.Data.Linq.Table<HOADON> HOADONs
		{
			get
			{
				return this.GetTable<HOADON>();
			}
		}
		
		public System.Data.Linq.Table<KHACHHANG> KHACHHANGs
		{
			get
			{
				return this.GetTable<KHACHHANG>();
			}
		}
		
		public System.Data.Linq.Table<THOIGIANSUDUNG> THOIGIANSUDUNGs
		{
			get
			{
				return this.GetTable<THOIGIANSUDUNG>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.CUOCTHUEBAO")]
	public partial class CUOCTHUEBAO : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDcuoc;
		
		private string _Tencuoc;
		
		private System.TimeSpan _TGBD;
		
		private System.TimeSpan _TGKT;
		
		private System.Nullable<double> _Gia;
		
		private System.Nullable<System.DateTime> _Ngayapdung;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDcuocChanging(string value);
    partial void OnIDcuocChanged();
    partial void OnTencuocChanging(string value);
    partial void OnTencuocChanged();
    partial void OnTGBDChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTGBDChanged();
    partial void OnTGKTChanging(System.Nullable<System.TimeSpan> value);
    partial void OnTGKTChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    partial void OnNgayapdungChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayapdungChanged();
    #endregion
		
		public CUOCTHUEBAO()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDcuoc", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDcuoc
		{
			get
			{
				return this._IDcuoc;
			}
			set
			{
				if ((this._IDcuoc != value))
				{
					this.OnIDcuocChanging(value);
					this.SendPropertyChanging();
					this._IDcuoc = value;
					this.SendPropertyChanged("IDcuoc");
					this.OnIDcuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tencuoc", DbType="NVarChar(50)")]
		public string Tencuoc
		{
			get
			{
				return this._Tencuoc;
			}
			set
			{
				if ((this._Tencuoc != value))
				{
					this.OnTencuocChanging(value);
					this.SendPropertyChanging();
					this._Tencuoc = value;
					this.SendPropertyChanged("Tencuoc");
					this.OnTencuocChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGBD", DbType="Time")]
		public System.TimeSpan TGBD
		{
			get
			{
				return this._TGBD;
			}
			set
			{
				if ((this._TGBD != value))
				{
					this.OnTGBDChanging(value);
					this.SendPropertyChanging();
					this._TGBD = value;
					this.SendPropertyChanged("TGBD");
					this.OnTGBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGKT", DbType="Time")]
		public System.TimeSpan TGKT
		{
			get
			{
				return this._TGKT;
			}
			set
			{
				if ((this._TGKT != value))
				{
					this.OnTGKTChanging(value);
					this.SendPropertyChanging();
					this._TGKT = value;
					this.SendPropertyChanged("TGKT");
					this.OnTGKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Ngayapdung", DbType="Date")]
		public System.Nullable<System.DateTime> Ngayapdung
		{
			get
			{
				return this._Ngayapdung;
			}
			set
			{
				if ((this._Ngayapdung != value))
				{
					this.OnNgayapdungChanging(value);
					this.SendPropertyChanging();
					this._Ngayapdung = value;
					this.SendPropertyChanged("Ngayapdung");
					this.OnNgayapdungChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THONGTINSIM")]
	public partial class THONGTINSIM : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDSim;
		
		private string _IDKHACHHANG;
		
		private string _Sdt;
		
		private System.Nullable<System.DateTime> _NgayDK;
		
		private System.Nullable<double> _CuocDK;
		
		private EntitySet<HOADON> _HOADONs;
		
		private EntitySet<THOIGIANSUDUNG> _THOIGIANSUDUNGs;
		
		private EntityRef<KHACHHANG> _KHACHHANG;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDSimChanging(string value);
    partial void OnIDSimChanged();
    partial void OnIDKHACHHANGChanging(string value);
    partial void OnIDKHACHHANGChanged();
    partial void OnSdtChanging(string value);
    partial void OnSdtChanged();
    partial void OnNgayDKChanging(System.Nullable<System.DateTime> value);
    partial void OnNgayDKChanged();
    partial void OnCuocDKChanging(System.Nullable<double> value);
    partial void OnCuocDKChanged();
    #endregion
		
		public THONGTINSIM()
		{
			this._HOADONs = new EntitySet<HOADON>(new Action<HOADON>(this.attach_HOADONs), new Action<HOADON>(this.detach_HOADONs));
			this._THOIGIANSUDUNGs = new EntitySet<THOIGIANSUDUNG>(new Action<THOIGIANSUDUNG>(this.attach_THOIGIANSUDUNGs), new Action<THOIGIANSUDUNG>(this.detach_THOIGIANSUDUNGs));
			this._KHACHHANG = default(EntityRef<KHACHHANG>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSim", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDSim
		{
			get
			{
				return this._IDSim;
			}
			set
			{
				if ((this._IDSim != value))
				{
					this.OnIDSimChanging(value);
					this.SendPropertyChanging();
					this._IDSim = value;
					this.SendPropertyChanged("IDSim");
					this.OnIDSimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKHACHHANG", DbType="VarChar(20)")]
		public string IDKHACHHANG
		{
			get
			{
				return this._IDKHACHHANG;
			}
			set
			{
				if ((this._IDKHACHHANG != value))
				{
					if (this._KHACHHANG.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._IDKHACHHANG = value;
					this.SendPropertyChanged("IDKHACHHANG");
					this.OnIDKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Sdt", DbType="VarChar(20)")]
		public string Sdt
		{
			get
			{
				return this._Sdt;
			}
			set
			{
				if ((this._Sdt != value))
				{
					this.OnSdtChanging(value);
					this.SendPropertyChanging();
					this._Sdt = value;
					this.SendPropertyChanged("Sdt");
					this.OnSdtChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_NgayDK", DbType="Date")]
		public System.Nullable<System.DateTime> NgayDK
		{
			get
			{
				return this._NgayDK;
			}
			set
			{
				if ((this._NgayDK != value))
				{
					this.OnNgayDKChanging(value);
					this.SendPropertyChanging();
					this._NgayDK = value;
					this.SendPropertyChanged("NgayDK");
					this.OnNgayDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CuocDK", DbType="Float")]
		public System.Nullable<double> CuocDK
		{
			get
			{
				return this._CuocDK;
			}
			set
			{
				if ((this._CuocDK != value))
				{
					this.OnCuocDKChanging(value);
					this.SendPropertyChanging();
					this._CuocDK = value;
					this.SendPropertyChanged("CuocDK");
					this.OnCuocDKChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINSIM_HOADON", Storage="_HOADONs", ThisKey="IDSim", OtherKey="IDsim")]
		public EntitySet<HOADON> HOADONs
		{
			get
			{
				return this._HOADONs;
			}
			set
			{
				this._HOADONs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINSIM_THOIGIANSUDUNG", Storage="_THOIGIANSUDUNGs", ThisKey="IDSim", OtherKey="IDSim")]
		public EntitySet<THOIGIANSUDUNG> THOIGIANSUDUNGs
		{
			get
			{
				return this._THOIGIANSUDUNGs;
			}
			set
			{
				this._THOIGIANSUDUNGs.Assign(value);
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THONGTINSIM", Storage="_KHACHHANG", ThisKey="IDKHACHHANG", OtherKey="IDKHACHHANG", IsForeignKey=true)]
		public KHACHHANG KHACHHANG
		{
			get
			{
				return this._KHACHHANG.Entity;
			}
			set
			{
				KHACHHANG previousValue = this._KHACHHANG.Entity;
				if (((previousValue != value) 
							|| (this._KHACHHANG.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._KHACHHANG.Entity = null;
						previousValue.THONGTINSIMs.Remove(this);
					}
					this._KHACHHANG.Entity = value;
					if ((value != null))
					{
						value.THONGTINSIMs.Add(this);
						this._IDKHACHHANG = value.IDKHACHHANG;
					}
					else
					{
						this._IDKHACHHANG = default(string);
					}
					this.SendPropertyChanged("KHACHHANG");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINSIM = this;
		}
		
		private void detach_HOADONs(HOADON entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINSIM = null;
		}
		
		private void attach_THOIGIANSUDUNGs(THOIGIANSUDUNG entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINSIM = this;
		}
		
		private void detach_THOIGIANSUDUNGs(THOIGIANSUDUNG entity)
		{
			this.SendPropertyChanging();
			entity.THONGTINSIM = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.HOADON")]
	public partial class HOADON : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDHD;
		
		private string _IDsim;
		
		private System.Nullable<System.DateTime> _TGBD;
		
		private System.Nullable<System.DateTime> _TGKT;
		
		private System.Nullable<double> _SophutBN;
		
		private System.Nullable<double> _SophutBD;
		
		private System.Nullable<double> _TongSoTien;
		
		private string _Trangthai;
		
		private EntityRef<THONGTINSIM> _THONGTINSIM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDHDChanging(string value);
    partial void OnIDHDChanged();
    partial void OnIDsimChanging(string value);
    partial void OnIDsimChanged();
    partial void OnTGBDChanging(System.Nullable<System.DateTime> value);
    partial void OnTGBDChanged();
    partial void OnTGKTChanging(System.Nullable<System.DateTime> value);
    partial void OnTGKTChanged();
    partial void OnSophutBNChanging(System.Nullable<double> value);
    partial void OnSophutBNChanged();
    partial void OnSophutBDChanging(System.Nullable<double> value);
    partial void OnSophutBDChanged();
    partial void OnTongSoTienChanging(System.Nullable<double> value);
    partial void OnTongSoTienChanged();
    partial void OnTrangthaiChanging(string value);
    partial void OnTrangthaiChanged();
    #endregion
		
		public HOADON()
		{
			this._THONGTINSIM = default(EntityRef<THONGTINSIM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDHD", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDHD
		{
			get
			{
				return this._IDHD;
			}
			set
			{
				if ((this._IDHD != value))
				{
					this.OnIDHDChanging(value);
					this.SendPropertyChanging();
					this._IDHD = value;
					this.SendPropertyChanged("IDHD");
					this.OnIDHDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDsim", DbType="VarChar(20)")]
		public string IDsim
		{
			get
			{
				return this._IDsim;
			}
			set
			{
				if ((this._IDsim != value))
				{
					if (this._THONGTINSIM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDsimChanging(value);
					this.SendPropertyChanging();
					this._IDsim = value;
					this.SendPropertyChanged("IDsim");
					this.OnIDsimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGBD", DbType="Date")]
		public System.Nullable<System.DateTime> TGBD
		{
			get
			{
				return this._TGBD;
			}
			set
			{
				if ((this._TGBD != value))
				{
					this.OnTGBDChanging(value);
					this.SendPropertyChanging();
					this._TGBD = value;
					this.SendPropertyChanged("TGBD");
					this.OnTGBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGKT", DbType="Date")]
		public System.Nullable<System.DateTime> TGKT
		{
			get
			{
				return this._TGKT;
			}
			set
			{
				if ((this._TGKT != value))
				{
					this.OnTGKTChanging(value);
					this.SendPropertyChanging();
					this._TGKT = value;
					this.SendPropertyChanged("TGKT");
					this.OnTGKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophutBN", DbType="Float")]
		public System.Nullable<double> SophutBN
		{
			get
			{
				return this._SophutBN;
			}
			set
			{
				if ((this._SophutBN != value))
				{
					this.OnSophutBNChanging(value);
					this.SendPropertyChanging();
					this._SophutBN = value;
					this.SendPropertyChanged("SophutBN");
					this.OnSophutBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophutBD", DbType="Float")]
		public System.Nullable<double> SophutBD
		{
			get
			{
				return this._SophutBD;
			}
			set
			{
				if ((this._SophutBD != value))
				{
					this.OnSophutBDChanging(value);
					this.SendPropertyChanging();
					this._SophutBD = value;
					this.SendPropertyChanged("SophutBD");
					this.OnSophutBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TongSoTien", DbType="Float")]
		public System.Nullable<double> TongSoTien
		{
			get
			{
				return this._TongSoTien;
			}
			set
			{
				if ((this._TongSoTien != value))
				{
					this.OnTongSoTienChanging(value);
					this.SendPropertyChanging();
					this._TongSoTien = value;
					this.SendPropertyChanged("TongSoTien");
					this.OnTongSoTienChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Trangthai", DbType="NVarChar(50)")]
		public string Trangthai
		{
			get
			{
				return this._Trangthai;
			}
			set
			{
				if ((this._Trangthai != value))
				{
					this.OnTrangthaiChanging(value);
					this.SendPropertyChanging();
					this._Trangthai = value;
					this.SendPropertyChanged("Trangthai");
					this.OnTrangthaiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINSIM_HOADON", Storage="_THONGTINSIM", ThisKey="IDsim", OtherKey="IDSim", IsForeignKey=true)]
		public THONGTINSIM THONGTINSIM
		{
			get
			{
				return this._THONGTINSIM.Entity;
			}
			set
			{
				THONGTINSIM previousValue = this._THONGTINSIM.Entity;
				if (((previousValue != value) 
							|| (this._THONGTINSIM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THONGTINSIM.Entity = null;
						previousValue.HOADONs.Remove(this);
					}
					this._THONGTINSIM.Entity = value;
					if ((value != null))
					{
						value.HOADONs.Add(this);
						this._IDsim = value.IDSim;
					}
					else
					{
						this._IDsim = default(string);
					}
					this.SendPropertyChanged("THONGTINSIM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.KHACHHANG")]
	public partial class KHACHHANG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _IDKHACHHANG;
		
		private string _Tenkhachhang;
		
		private string _CMND;
		
		private string _Nghenghiep;
		
		private string _Chucvu;
		
		private string _Diachi;
		
		private string _Email;
		
		private EntitySet<THONGTINSIM> _THONGTINSIMs;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnIDKHACHHANGChanging(string value);
    partial void OnIDKHACHHANGChanged();
    partial void OnTenkhachhangChanging(string value);
    partial void OnTenkhachhangChanged();
    partial void OnCMNDChanging(string value);
    partial void OnCMNDChanged();
    partial void OnNghenghiepChanging(string value);
    partial void OnNghenghiepChanged();
    partial void OnChucvuChanging(string value);
    partial void OnChucvuChanged();
    partial void OnDiachiChanging(string value);
    partial void OnDiachiChanged();
    partial void OnEmailChanging(string value);
    partial void OnEmailChanged();
    #endregion
		
		public KHACHHANG()
		{
			this._THONGTINSIMs = new EntitySet<THONGTINSIM>(new Action<THONGTINSIM>(this.attach_THONGTINSIMs), new Action<THONGTINSIM>(this.detach_THONGTINSIMs));
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDKHACHHANG", DbType="VarChar(20) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string IDKHACHHANG
		{
			get
			{
				return this._IDKHACHHANG;
			}
			set
			{
				if ((this._IDKHACHHANG != value))
				{
					this.OnIDKHACHHANGChanging(value);
					this.SendPropertyChanging();
					this._IDKHACHHANG = value;
					this.SendPropertyChanged("IDKHACHHANG");
					this.OnIDKHACHHANGChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Tenkhachhang", DbType="NVarChar(100)")]
		public string Tenkhachhang
		{
			get
			{
				return this._Tenkhachhang;
			}
			set
			{
				if ((this._Tenkhachhang != value))
				{
					this.OnTenkhachhangChanging(value);
					this.SendPropertyChanging();
					this._Tenkhachhang = value;
					this.SendPropertyChanged("Tenkhachhang");
					this.OnTenkhachhangChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_CMND", DbType="Char(20)")]
		public string CMND
		{
			get
			{
				return this._CMND;
			}
			set
			{
				if ((this._CMND != value))
				{
					this.OnCMNDChanging(value);
					this.SendPropertyChanging();
					this._CMND = value;
					this.SendPropertyChanged("CMND");
					this.OnCMNDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Nghenghiep", DbType="NVarChar(100)")]
		public string Nghenghiep
		{
			get
			{
				return this._Nghenghiep;
			}
			set
			{
				if ((this._Nghenghiep != value))
				{
					this.OnNghenghiepChanging(value);
					this.SendPropertyChanging();
					this._Nghenghiep = value;
					this.SendPropertyChanged("Nghenghiep");
					this.OnNghenghiepChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Chucvu", DbType="NVarChar(100)")]
		public string Chucvu
		{
			get
			{
				return this._Chucvu;
			}
			set
			{
				if ((this._Chucvu != value))
				{
					this.OnChucvuChanging(value);
					this.SendPropertyChanging();
					this._Chucvu = value;
					this.SendPropertyChanged("Chucvu");
					this.OnChucvuChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Diachi", DbType="Text", UpdateCheck=UpdateCheck.Never)]
		public string Diachi
		{
			get
			{
				return this._Diachi;
			}
			set
			{
				if ((this._Diachi != value))
				{
					this.OnDiachiChanging(value);
					this.SendPropertyChanging();
					this._Diachi = value;
					this.SendPropertyChanged("Diachi");
					this.OnDiachiChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Email", DbType="VarChar(100)")]
		public string Email
		{
			get
			{
				return this._Email;
			}
			set
			{
				if ((this._Email != value))
				{
					this.OnEmailChanging(value);
					this.SendPropertyChanging();
					this._Email = value;
					this.SendPropertyChanged("Email");
					this.OnEmailChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="KHACHHANG_THONGTINSIM", Storage="_THONGTINSIMs", ThisKey="IDKHACHHANG", OtherKey="IDKHACHHANG")]
		public EntitySet<THONGTINSIM> THONGTINSIMs
		{
			get
			{
				return this._THONGTINSIMs;
			}
			set
			{
				this._THONGTINSIMs.Assign(value);
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
		
		private void attach_THONGTINSIMs(THONGTINSIM entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = this;
		}
		
		private void detach_THONGTINSIMs(THONGTINSIM entity)
		{
			this.SendPropertyChanging();
			entity.KHACHHANG = null;
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.THOIGIANSUDUNG")]
	public partial class THOIGIANSUDUNG : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _STT;
		
		private string _IDSim;
		
		private System.Nullable<System.DateTime> _TGBD;
		
		private System.Nullable<System.DateTime> _TGKT;
		
		private System.Nullable<double> _SophutBN;
		
		private System.Nullable<double> _SophutBD;
		
		private System.Nullable<double> _Gia;
		
		private EntityRef<THONGTINSIM> _THONGTINSIM;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnSTTChanging(int value);
    partial void OnSTTChanged();
    partial void OnIDSimChanging(string value);
    partial void OnIDSimChanged();
    partial void OnTGBDChanging(System.Nullable<System.DateTime> value);
    partial void OnTGBDChanged();
    partial void OnTGKTChanging(System.Nullable<System.DateTime> value);
    partial void OnTGKTChanged();
    partial void OnSophutBNChanging(System.Nullable<double> value);
    partial void OnSophutBNChanged();
    partial void OnSophutBDChanging(System.Nullable<double> value);
    partial void OnSophutBDChanged();
    partial void OnGiaChanging(System.Nullable<double> value);
    partial void OnGiaChanged();
    #endregion
		
		public THOIGIANSUDUNG()
		{
			this._THONGTINSIM = default(EntityRef<THONGTINSIM>);
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_STT", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int STT
		{
			get
			{
				return this._STT;
			}
			set
			{
				if ((this._STT != value))
				{
					this.OnSTTChanging(value);
					this.SendPropertyChanging();
					this._STT = value;
					this.SendPropertyChanged("STT");
					this.OnSTTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IDSim", DbType="VarChar(20) NOT NULL", CanBeNull=false)]
		public string IDSim
		{
			get
			{
				return this._IDSim;
			}
			set
			{
				if ((this._IDSim != value))
				{
					if (this._THONGTINSIM.HasLoadedOrAssignedValue)
					{
						throw new System.Data.Linq.ForeignKeyReferenceAlreadyHasValueException();
					}
					this.OnIDSimChanging(value);
					this.SendPropertyChanging();
					this._IDSim = value;
					this.SendPropertyChanged("IDSim");
					this.OnIDSimChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGBD", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGBD
		{
			get
			{
				return this._TGBD;
			}
			set
			{
				if ((this._TGBD != value))
				{
					this.OnTGBDChanging(value);
					this.SendPropertyChanging();
					this._TGBD = value;
					this.SendPropertyChanged("TGBD");
					this.OnTGBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TGKT", DbType="DateTime")]
		public System.Nullable<System.DateTime> TGKT
		{
			get
			{
				return this._TGKT;
			}
			set
			{
				if ((this._TGKT != value))
				{
					this.OnTGKTChanging(value);
					this.SendPropertyChanging();
					this._TGKT = value;
					this.SendPropertyChanged("TGKT");
					this.OnTGKTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophutBN", DbType="Float")]
		public System.Nullable<double> SophutBN
		{
			get
			{
				return this._SophutBN;
			}
			set
			{
				if ((this._SophutBN != value))
				{
					this.OnSophutBNChanging(value);
					this.SendPropertyChanging();
					this._SophutBN = value;
					this.SendPropertyChanged("SophutBN");
					this.OnSophutBNChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_SophutBD", DbType="Float")]
		public System.Nullable<double> SophutBD
		{
			get
			{
				return this._SophutBD;
			}
			set
			{
				if ((this._SophutBD != value))
				{
					this.OnSophutBDChanging(value);
					this.SendPropertyChanging();
					this._SophutBD = value;
					this.SendPropertyChanged("SophutBD");
					this.OnSophutBDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Gia", DbType="Float")]
		public System.Nullable<double> Gia
		{
			get
			{
				return this._Gia;
			}
			set
			{
				if ((this._Gia != value))
				{
					this.OnGiaChanging(value);
					this.SendPropertyChanging();
					this._Gia = value;
					this.SendPropertyChanged("Gia");
					this.OnGiaChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.AssociationAttribute(Name="THONGTINSIM_THOIGIANSUDUNG", Storage="_THONGTINSIM", ThisKey="IDSim", OtherKey="IDSim", IsForeignKey=true)]
		public THONGTINSIM THONGTINSIM
		{
			get
			{
				return this._THONGTINSIM.Entity;
			}
			set
			{
				THONGTINSIM previousValue = this._THONGTINSIM.Entity;
				if (((previousValue != value) 
							|| (this._THONGTINSIM.HasLoadedOrAssignedValue == false)))
				{
					this.SendPropertyChanging();
					if ((previousValue != null))
					{
						this._THONGTINSIM.Entity = null;
						previousValue.THOIGIANSUDUNGs.Remove(this);
					}
					this._THONGTINSIM.Entity = value;
					if ((value != null))
					{
						value.THOIGIANSUDUNGs.Add(this);
						this._IDSim = value.IDSim;
					}
					else
					{
						this._IDSim = default(string);
					}
					this.SendPropertyChanged("THONGTINSIM");
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
